### ISSUE TITLE
extract equations in tables and cells 

### ISSUE THREAD

**Issue by arth17singh** [hrushikeshrv/docxlatex#2]
using document.get_text() method might work on documents but I see no way of extracting equations inside a table or a cell. Like in python-docx there is a support of tables and cells and text in a cell can be extracted by cell.text, but how do I use docxlatex to extract the equations and the text only in a particular cell of a table ?

**Comment by arth17singh** [comment]
if there would be a method cell.get_text() it would have been great as it would add the support of extracting equations from the tables

**Comment by hrushikeshrv** [comment]
Thanks for the issue @arth17singh. Unfortunately, there is no way to extract equations from a particular cell. `docxlatex` is a simple parser and just extracts the entire text of the document at once, unlike `python-docx`, which builds the XML tree for the document as attributes on the `Document` class.

To add support for what you suggest will take some considerable amount of work, and unfortunately I can't dedicate that much time to this project right now. However, I think that it might be possible to support extraction of equations by modifying the source code for `python-docx`. If you really need to extract equations in particular cells, you may want to fork `python-docx` and implement the equation extraction used in this library.

**Comment by hrushikeshrv** [comment]
That's great! Glad `docxlatex` could help someone :)
